spring:
  application:
    name: asm2
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041;encrypt=true;trustServerCertificate=true;"
    username: sa
    password: 123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

user:
  key: "uwUtv8oxZmhI9NQPRNdxkhndhiRyPRHpViRMhgnZYML6WGNUon8fqHAYZ18BKCj3"